apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-monnom-MonApplication-frontend-cert
  namespace: dev-monnom-MonApplication-frontend
spec:
  secretName: dev-monnom-MonApplication-frontend-tls
  dnsNames:
    - dev.monsousdomain2.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
