apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-monnom-MonApplication-frontend-cert
  namespace: staging-monnom-MonApplication-frontend
spec:
  secretName: staging-monnom-MonApplication-frontend-tls
  dnsNames:
    - staging.monsousdomain2.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
